
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CuoiKi
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {

        this.Lineitems = new HashSet<Lineitem>();

    }


    public int item_id { get; set; }

    public string item_name { get; set; }

    public Nullable<double> item_price_in { get; set; }

    public Nullable<double> item_price_out { get; set; }

    public Nullable<int> quantity_in_stock { get; set; }

    public Nullable<System.DateTime> expiry { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Lineitem> Lineitems { get; set; }

}

}
