//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLyThuVien : DbContext
    {
        public QLyThuVien()
            : base("name=QLyThuVien")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Muon_sach> Muon_sach { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<Thedocgia> Thedocgias { get; set; }
        public virtual DbSet<Thu_vien> Thu_vien { get; set; }
        public virtual DbSet<Thuthu> Thuthus { get; set; }
    }
}
