
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CuoiKi
{

using System;
    using System.Collections.Generic;
    
public partial class Voucher
{

    public int ma_voucher { get; set; }

    public Nullable<double> gia_voucher { get; set; }

}

}
